version: "3.9"  # optional since v1.27.0
services: 
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./collector/config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
    environment:
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}

  refinery:
    image: honeycombio/refinery:latest
    volumes:
      - ./refinery/config.yaml:/etc/refinery/refinery.yaml
      - ./refinery/rules.yaml:/etc/refinery/rules.yaml
    environment:
      - REFINERY_HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
